blank_issues_enabled: true
contact_links:
  - name: Discord 🫧
    url: https://discord.gg/jQXnYeQGTe
    about: Join us!
  - name: Mastodon 🦣
    url: https://moth.social/@mammoth
    about: Follow us!
